import { OpticAttachmentConfig, OpticType, WeaponConfig, WeaponType } from '../types';

export const OPTIC_REGISTRY: Record<OpticType, OpticAttachmentConfig> = {
  iron_sight: {
    id: 'iron_sight',
    name: 'Factory Iron Sights',
    category: 'Iron Sights',
    desc: 'High-visibility tritium night sight dots. Fastest target acquisition (+15% ADS Speed).',
    magnification: 1.0,
    adsFov: 68,
    adsSpeedMultiplier: 1.15,
    swayMultiplier: 1.0,
    compatibleWeapons: ['m4', 'mp5', 'sniper', 'shotgun', 'deagle'],
  },
  reflex_dot: {
    id: 'reflex_dot',
    name: 'Micro Reflex T-2',
    category: 'Reflex Sight',
    desc: 'Ultra-crisp 2-MOA red dot optic with anti-glare multi-coated lens and low-profile bezel.',
    description: 'Ultra-crisp 2-MOA red dot optic with anti-glare multi-coated lens and low-profile bezel.',
    magnification: 1.35,
    adsFov: 58,
    adsSpeedMultiplier: 1.05,
    swayMultiplier: 0.9,
    compatibleWeapons: ['m4', 'mp5', 'sniper', 'shotgun', 'deagle'],
  },
  red_dot_micro: {
    id: 'red_dot_micro',
    name: 'Aimpoint Micro T-2 Red Dot',
    category: 'Reflex Sight',
    desc: 'Ultra-crisp 2-MOA red dot optic with anti-glare multi-coated lens and low-profile bezel.',
    description: 'Ultra-crisp 2-MOA red dot optic with anti-glare multi-coated lens and low-profile bezel.',
    magnification: 1.35,
    adsFov: 58,
    adsSpeedMultiplier: 1.05,
    swayMultiplier: 0.9,
    compatibleWeapons: ['m4', 'mp5', 'sniper', 'shotgun', 'deagle'],
  },
  holo_553: {
    id: 'holo_553',
    name: 'Holo 553 Holographic',
    category: 'Holographic',
    desc: 'Mil-spec 68-MOA outer halo ring with 1-MOA center aiming dot. Unobstructed CQB view.',
    description: 'Mil-spec 68-MOA outer halo ring with 1-MOA center aiming dot. Unobstructed CQB view.',
    magnification: 1.5,
    adsFov: 54,
    adsSpeedMultiplier: 1.0,
    swayMultiplier: 0.85,
    compatibleWeapons: ['m4', 'mp5', 'shotgun', 'deagle'],
  },
  acog_4x: {
    id: 'acog_4x',
    name: 'ACOG 4.0X Combat Optic',
    category: 'Combat Scope',
    desc: '4.0X magnification prism scope with fiber-optic illuminated chevron and BDC stadia.',
    description: '4.0X magnification prism scope with fiber-optic illuminated chevron and BDC stadia.',
    magnification: 4.0,
    adsFov: 36,
    adsSpeedMultiplier: 0.88,
    swayMultiplier: 0.75,
    hasFullScopeOverlay: true,
    hasRangefinder: true,
    compatibleWeapons: ['m4', 'mp5', 'sniper', 'deagle'],
  },
  sniper_variable: {
    id: 'sniper_variable',
    name: 'Nightforce ATACR Variable 4.5X-10X',
    category: 'Sniper Scope',
    desc: 'Dual-focal variable optic with Mil-Dot stadia, laser rangefinder telemetry, and steady breath hold.',
    description: 'Dual-focal variable optic with Mil-Dot stadia, laser rangefinder telemetry, and steady breath hold.',
    magnification: 8.5,
    adsFov: 24,
    adsSpeedMultiplier: 0.82,
    swayMultiplier: 0.65,
    isVariableZoom: true,
    hasFullScopeOverlay: true,
    variableZoomSteps: [4.5, 10.0],
    hasRangefinder: true,
    zoomLevels: [
      { label: '4.5X TACTICAL', fov: 32, mag: 4.5 },
      { label: '10.0X EXTREME', fov: 14, mag: 10.0 },
    ],
    compatibleWeapons: ['sniper', 'm4'],
  },
  thermal_flir: {
    id: 'thermal_flir',
    name: 'FLIR ThermoSight Pro',
    category: 'Thermal Optic',
    desc: 'FLIR 60Hz thermal spectrum processor detecting heat signatures through darkness and smoke.',
    description: 'FLIR 60Hz thermal spectrum processor detecting heat signatures through darkness and smoke.',
    magnification: 3.5,
    adsFov: 40,
    adsSpeedMultiplier: 0.85,
    swayMultiplier: 0.8,
    isThermal: true,
    hasFullScopeOverlay: true,
    hasThermalVision: true,
    hasRangefinder: true,
    compatibleWeapons: ['m4', 'mp5', 'sniper', 'deagle'],
  },
  thermal_ir: {
    id: 'thermal_ir',
    name: 'FLIR ThermoSight Pro 3.5X',
    category: 'Thermal Optic',
    desc: 'FLIR 60Hz thermal spectrum processor detecting heat signatures through darkness and smoke.',
    description: 'FLIR 60Hz thermal spectrum processor detecting heat signatures through darkness and smoke.',
    magnification: 3.5,
    adsFov: 40,
    adsSpeedMultiplier: 0.85,
    swayMultiplier: 0.8,
    isThermal: true,
    hasFullScopeOverlay: true,
    hasThermalVision: true,
    hasRangefinder: true,
    compatibleWeapons: ['m4', 'mp5', 'sniper', 'deagle'],
  },
};

export const DEFAULT_WEAPON_OPTICS: Record<WeaponType, OpticType> = {
  m4: 'holo_553',
  mp5: 'reflex_dot',
  sniper: 'sniper_variable',
  shotgun: 'iron_sight',
  deagle: 'reflex_dot',
};

export const WEAPON_REGISTRY: Record<WeaponType, WeaponConfig> = {
  m4: {
    id: 'm4',
    name: 'M4A1 Assault Rifle',
    category: 'Assault Rifle',
    damage: 34,
    headshotMultiplier: 2.1,
    fireRateRpm: 800, // ~75ms per shot
    magSize: 30,
    totalReserve: 120,
    reloadTimeSec: 2.3, // Full empty reload (mag out + new mag + bolt release)
    tacticalReloadTimeSec: 1.45, // Tactical reload (round chambered: fast mag swap)
    range: 90,
    spreadHip: 0.035,
    spreadAds: 0.0025,
    recoilVertical: 0.032,
    recoilHorizontal: 0.012,
    recoilSpringRate: 24.0,
    recoilDampingRate: 18.0,
    // Realistic spray pattern curve (x = yaw drift, y = pitch climb)
    recoilPattern: [
      { x: 0.0, y: 0.028 },
      { x: 0.002, y: 0.032 },
      { x: 0.006, y: 0.036 },
      { x: 0.012, y: 0.038 },
      { x: 0.016, y: 0.034 },
      { x: 0.014, y: 0.030 },
      { x: 0.005, y: 0.028 },
      { x: -0.008, y: 0.026 },
      { x: -0.015, y: 0.028 },
      { x: -0.012, y: 0.030 },
      { x: 0.002, y: 0.032 },
      { x: 0.010, y: 0.032 },
    ],
    adsSpeed: 0.22,
    adsFov: 55,
    fullAuto: true,
    soundPitch: 1.0,
    muzzleVelocity: 880, // 880 m/s 5.56 NATO
    bulletDropRate: 1.0,
    dragFactor: 0.0018,
    damageFalloffStart: 40,
    damageFalloffEnd: 85,
    minDamage: 21,
    penetrationPower: 2,
    swayAmplitude: 0.0032,
    swaySpeed: 1.8,
  },
  mp5: {
    id: 'mp5',
    name: 'MP5 Submachine Gun',
    category: 'SMG',
    damage: 26,
    headshotMultiplier: 1.8,
    fireRateRpm: 920, // High cadence
    magSize: 30,
    totalReserve: 150,
    reloadTimeSec: 1.9, // Full empty reload (mag out + slap lock handle)
    tacticalReloadTimeSec: 1.2, // Tactical reload (fast mag retention swap)
    range: 55,
    spreadHip: 0.022,
    spreadAds: 0.004,
    recoilVertical: 0.022,
    recoilHorizontal: 0.016,
    recoilSpringRate: 30.0,
    recoilDampingRate: 22.0,
    recoilPattern: [
      { x: 0.0, y: 0.020 },
      { x: -0.004, y: 0.022 },
      { x: 0.006, y: 0.024 },
      { x: -0.008, y: 0.022 },
      { x: 0.010, y: 0.020 },
      { x: -0.006, y: 0.022 },
      { x: 0.008, y: 0.024 },
      { x: -0.005, y: 0.020 },
    ],
    adsSpeed: 0.16,
    adsFov: 60,
    fullAuto: true,
    soundPitch: 1.1,
    muzzleVelocity: 400, // 400 m/s 9mm Parabellum
    bulletDropRate: 1.4,
    dragFactor: 0.0035,
    damageFalloffStart: 22,
    damageFalloffEnd: 50,
    minDamage: 14,
    penetrationPower: 1,
    swayAmplitude: 0.0026,
    swaySpeed: 2.2,
  },
  sniper: {
    id: 'sniper',
    name: 'AX-50 .50 Cal Sniper',
    category: 'Sniper Rifle',
    damage: 135, // 1-shot kill upper torso/head
    headshotMultiplier: 3.0,
    fireRateRpm: 45, // Bolt action
    magSize: 5,
    totalReserve: 25,
    reloadTimeSec: 3.2, // Full empty reload (heavy box mag + straight pull chambering)
    tacticalReloadTimeSec: 2.0, // Tactical reload
    range: 220,
    spreadHip: 0.14,
    spreadAds: 0.0003,
    recoilVertical: 0.14,
    recoilHorizontal: 0.03,
    recoilSpringRate: 12.0,
    recoilDampingRate: 9.0,
    recoilPattern: [
      { x: 0.01, y: 0.14 },
      { x: -0.015, y: 0.15 },
    ],
    adsSpeed: 0.38,
    adsFov: 24, // High magnification optical zoom
    fullAuto: false,
    soundPitch: 0.85,
    muzzleVelocity: 950, // 950 m/s .50 BMG Heavy round
    bulletDropRate: 0.65, // Flatter trajectory
    dragFactor: 0.0009,
    damageFalloffStart: 100,
    damageFalloffEnd: 220,
    minDamage: 105,
    penetrationPower: 3, // Heavy penetration through multiple covers
    swayAmplitude: 0.0065, // Breathing sway visible in optic
    swaySpeed: 1.2,
  },
  shotgun: {
    id: 'shotgun',
    name: 'Model 680 Breacher',
    category: 'Shotgun',
    damage: 24, // Per pellet
    pelletCount: 8, // Total ~192 max point blank
    headshotMultiplier: 1.5,
    fireRateRpm: 75,
    magSize: 8,
    totalReserve: 32,
    reloadTimeSec: 2.8, // Full empty reload (shell feed + pump cycle)
    tacticalReloadTimeSec: 1.8, // Tactical speed feed reload
    range: 30,
    spreadHip: 0.075,
    spreadAds: 0.032,
    recoilVertical: 0.095,
    recoilHorizontal: 0.025,
    recoilSpringRate: 16.0,
    recoilDampingRate: 12.0,
    recoilPattern: [
      { x: 0.005, y: 0.095 },
      { x: -0.008, y: 0.10 },
    ],
    adsSpeed: 0.24,
    adsFov: 65,
    fullAuto: false,
    soundPitch: 0.95,
    muzzleVelocity: 380, // 380 m/s 12 Gauge buckshot
    bulletDropRate: 1.6,
    dragFactor: 0.006,
    damageFalloffStart: 10,
    damageFalloffEnd: 28,
    minDamage: 6,
    penetrationPower: 1,
    swayAmplitude: 0.004,
    swaySpeed: 1.6,
  },
  deagle: {
    id: 'deagle',
    name: '.50 GS Hand Cannon',
    category: 'Handgun',
    damage: 72,
    headshotMultiplier: 2.2, // 1-shot headshot close range
    fireRateRpm: 240,
    magSize: 7,
    totalReserve: 35,
    reloadTimeSec: 1.7, // Full empty reload (drop mag + insert mag + slide release)
    tacticalReloadTimeSec: 1.05, // Tactical reload (fast combat mag swap)
    range: 50,
    spreadHip: 0.045,
    spreadAds: 0.0035,
    recoilVertical: 0.07,
    recoilHorizontal: 0.02,
    recoilSpringRate: 22.0,
    recoilDampingRate: 15.0,
    recoilPattern: [
      { x: 0.004, y: 0.07 },
      { x: -0.006, y: 0.075 },
      { x: 0.008, y: 0.078 },
      { x: -0.005, y: 0.072 },
    ],
    adsSpeed: 0.14,
    adsFov: 62,
    fullAuto: false,
    soundPitch: 1.05,
    muzzleVelocity: 470, // 470 m/s .50 Action Express
    bulletDropRate: 1.2,
    dragFactor: 0.0028,
    damageFalloffStart: 25,
    damageFalloffEnd: 48,
    minDamage: 36,
    penetrationPower: 2,
    swayAmplitude: 0.0024,
    swaySpeed: 2.0,
  },
};


// Viewmodel positioning offsets for standard hipfire and ADS alignment
export const WEAPON_VIEWMODEL_OFFSETS: Record<
  WeaponType,
  {
    hip: { x: number; y: number; z: number; rx: number; ry: number; rz: number };
    ads: { x: number; y: number; z: number; rx: number; ry: number; rz: number };
    sprint: { x: number; y: number; z: number; rx: number; ry: number; rz: number };
  }
> = {
  m4: {
    hip: { x: 0.22, y: -0.22, z: -0.42, rx: 0.04, ry: -0.04, rz: 0.02 },
    ads: { x: 0.0, y: -0.13, z: -0.30, rx: 0, ry: 0, rz: 0 },
    sprint: { x: 0.24, y: -0.28, z: -0.36, rx: 0.65, ry: -0.5, rz: 0.3 },
  },
  mp5: {
    hip: { x: 0.2, y: -0.2, z: -0.38, rx: 0.03, ry: -0.03, rz: 0.02 },
    ads: { x: 0.0, y: -0.108, z: -0.28, rx: 0, ry: 0, rz: 0 },
    sprint: { x: 0.22, y: -0.25, z: -0.32, rx: 0.7, ry: -0.55, rz: 0.35 },
  },
  sniper: {
    hip: { x: 0.24, y: -0.24, z: -0.48, rx: 0.05, ry: -0.05, rz: 0.03 },
    ads: { x: 0.0, y: -0.155, z: -0.26, rx: 0, ry: 0, rz: 0 },
    sprint: { x: 0.26, y: -0.3, z: -0.4, rx: 0.8, ry: -0.6, rz: 0.4 },
  },
  shotgun: {
    hip: { x: 0.22, y: -0.2, z: -0.42, rx: 0.04, ry: -0.04, rz: 0.02 },
    ads: { x: 0.0, y: -0.085, z: -0.32, rx: 0, ry: 0, rz: 0 },
    sprint: { x: 0.24, y: -0.26, z: -0.36, rx: 0.68, ry: -0.52, rz: 0.32 },
  },
  deagle: {
    hip: { x: 0.16, y: -0.18, z: -0.35, rx: 0.02, ry: -0.02, rz: 0.01 },
    ads: { x: 0.0, y: -0.11, z: -0.28, rx: 0, ry: 0, rz: 0 },
    sprint: { x: 0.18, y: -0.24, z: -0.3, rx: 0.6, ry: -0.45, rz: 0.28 },
  },
};
